default: &default
  host: "localhost"
  port: 5432
  adapter: postgresql
  database: "student_inventory_development"
  pool: 5
  timeout: 5000
  username: "sms"
  password: "123456"
  su_username: "sms"
  su_password: "123456"


development:
  <<: *default


test:
  host: "localhost"
  port: 5432
  adapter: postgresql
  database: "student_inventory_test"
  pool: 5
  timeout: 5000
  username: "sms"
  password: "123456"
  su_username: "sms"
  su_password: "123456"


production:
  host: "localhost"
  port: 5432
  adapter: postgresql
  database: "student_inventory_production"
  pool: 5
  timeout: 5000
  username: "sms"
  password: "123456"
  su_username: "sms"
  su_password: "123456"